### ISSUE TITLE
vue中的样式提取不出来呢？

### ISSUE THREAD

**Issue by ljlstc123456** [webfansplz/xc-cli#1]

**Comment by webfansplz** [comment]
已解决！

**Comment by ljlstc123456** [comment]
除了这一部分修改了。还有其他原因吗？ 单双引号有关系吗？
`
const buildVueLoaderConf = Object.assign({}, baseVueLoaderConf, {
  loaders: {
    css: ExtractTextPlugin.extract({
      use: ['css-loader', 'postcss-loader'],
      fallback: 'vue-style-loader'
    }),
    less: ExtractTextPlugin.extract({
      use: ['css-loader', 'postcss-loader', 'less-loader'],
      fallback: 'vue-style-loader'
    })
  },
  cssSourceMap: false
});
`
