### ISSUE TITLE
为什么App组件提示未注册

### ISSUE THREAD

**Issue by cjchnwscqwsbsy** [webfansplz/xc-cli#2]
vue.js?ba4c:597 [Vue warn]: Unknown custom element: <App> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by webfansplz** [comment]
我这边运行正常的哦，请问是什么环境呢

**Comment by cjchnwscqwsbsy** [comment]
这跟环境有关系吗「◦㉨◦」，在Mac上跑的！发自我的华为手机-------- 原始邮件 --------主题：Re: [webfansplz/xc-cli] 为什么App组件提示未注册 (#2)发件人：webfansplz 收件人：webfansplz/xc-cli 抄送：纳兰禛祎 <18506166570@163.com>,Author 我这边运行正常的哦，请问是什么环境呢

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/webfansplz/xc-cli","title":"webfansplz/xc-cli","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/webfansplz/xc-cli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@webfansplz in #2: 我这边运行正常的哦，请问是什么环境呢"}],"action":{"name":"View Issue","url":"https://github.com/webfansplz/xc-cli/issues/2#issuecomment-442345301"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/webfansplz/xc-cli/issues/2#issuecomment-442345301",
"url": "https://github.com/webfansplz/xc-cli/issues/2#issuecomment-442345301",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [webfansplz/xc-cli] 为什么App组件提示未注册 (#2)",
"sections": [
{
"text": "",
"activityTitle": "**webfansplz**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@webfansplz",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"webfansplz/xc-cli\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"webfansplz/xc-cli\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/webfansplz/xc-cli/issues/2#issuecomment-442345301"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415902141\n}"
}
],
"themeColor": "26292E"
}
]
